### ISSUE TITLE
Invalid babel-loader

### ISSUE THREAD

**Issue by ellis2323** [mubaidr/vue-chrome-extension-boilerplate#176]
Babel loader 8 need @babel-core and not babel-core. This is a major change and you need to change multiple packages & .babelrc

**Comment by mubaidr** [comment]
Sure, will update it.

It you are i terested please create pull request? ;)

**Comment by mubaidr** [comment]
https://github.com/mubaidr/vue-chrome-extension-boilerplate/commit/67631ae69364242a68691da71770333605520741
