### ISSUE TITLE
npm vulnerabilities because of zip-folder

### ISSUE THREAD

**Issue by ellis2424** [mubaidr/vue-chrome-extension-boilerplate#177]
this package seems outdated. You could use zip-a-folder otherwise.

zip-folder specify 0.3 for the version of minimatch and not ^0.3.0.

**Comment by mubaidr** [comment]
`zip-a-folder` is abandoned too, added `node-archiver`.

https://github.com/mubaidr/vue-chrome-extension-boilerplate/commit/9b5771296e320bd813d5bc93ad6651e6d67e3678
