### ISSUE TITLE
dist files incomplete

### ISSUE THREAD

**Issue by papoola** [mubaidr/vue-chrome-extension-boilerplate#203]
First of all thanks @mubaidr for this amazing boilerplate. I love it!

I have updated icons and I feel like since then following problem started. Upon changing source files, sometimes `dist/icons` folder becomes empty, or `dist/manifest.json` is not created. Restarting `yarn dev` solves the issue but its slowing down the development. Can you think of a solution ?

**Comment by mubaidr** [comment]
I think this is the issue: https://github.com/mubaidr/vue-chrome-extension-boilerplate/blob/master/webpack.config.js#L92

Comment out this line and then try please. I will update this repo soon.

**Comment by papoola** [comment]
Thanks, that solved it ! There is one more thing I can't get to work for which I will create a separate issue.
