### ISSUE TITLE
Logo Proporsal

### ISSUE THREAD

**Issue by tjulises** [mubaidr/vue-chrome-extension-boilerplate#26]
Hi @mubaidr  ,

My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by mubaidr** [comment]
Hello TJ! That would be great!  

I do need logos for some other opensource projects, I will tag you. Thank you

**Comment by tjulises** [comment]
@mubaidr 

I'd also like to ask some questions (towards the logo-making)

What's the name that should be displayed on the logo, If there should be any.

How would you describe this project,
what is it intended to do?

What would you like this logo to transmit?

this little details are going to help me transmit what it's supposed to.

I'll look forward for your reply, cheers!

**Comment by mubaidr** [comment]
The main thing is: `Boilerplate for Chrome extension using Vue.js`

So anything you like and that can represent this line is good.
