### ISSUE TITLE
TypeError: CleanWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by anrichb** [mubaidr/vue-chrome-extension-boilerplate#261]
*NOT A DEVELOPER*
I cloned the repo and kept running into 'TypeError: CleanWebpackPlugin is not a constructor'. I checked and you were using the correct version of https://www.npmjs.com/package/clean-webpack-plugin as well as the correct way to instantiate:

  plugins: [
    new VueLoaderPlugin(),
    new CleanWebpackPlugin(),
    new CopyWebpackPlugin([
      { from: 'assets', to: 'assets' },
      { from: 'manifest.json', to: 'manifest.json', flatten: true },
    ]),

But the way you were including the module has to be updated:
/Users/..../vue-chrome-extension-boilerplate/webpack.config.js

// const CleanWebpackPlugin = require('clean-webpack-plugin')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')

Once I made that change it all worked :)

Again sorry if this is a bad write-up/incorrect -> im not a developer!

**Comment by mubaidr** [comment]
Thanks, fixed in: https://github.com/mubaidr/vue-chrome-extension-boilerplate/commit/e6abc2d9449a88a751f2ab87f42c4f1379946200
