### ISSUE TITLE
HMR vs Live Reloading

### ISSUE THREAD

**Issue by franciscolourenco** [mubaidr/vue-chrome-extension-boilerplate#370]
Is this boilerplate based on webpack-extension-reloader ?

If so I believe HMR is not yet supported. Only live reload - automatic page reload, not individual module reload. 
You might want to update the description to avoid confusion.

**Comment by mubaidr** [comment]
Somehow I missed it, you are right.

fixed in: https://github.com/mubaidr/vue-chrome-extension-boilerplate/commit/5791b5a4818871998dfaf858715ac43e297197e1
