### ISSUE TITLE
Unable to build stylus code in App.vue <style>

### ISSUE THREAD

**Issue by andrewmackie** [mubaidr/vue-chrome-extension-boilerplate#425]
Thanks for this boilerplate!

I'm having trouble using stylus (instead of vanilla CSS) in the style element of App.vue:

    <style lang="stylus">
        div
          background-color green
    </style>

On build I receive the following error:

    ERROR in ./popup/App.vue?vue&type=style&index=0&lang=stylus& (../node_modules/vue-loader/lib??vue-loader-options!./popup/App.vue?vue&type=style&index=0&lang=stylus&) 19:18
    Module parse failed: Unexpected token (19:18)
    File was processed with these loaders:
     * ../node_modules/vue-loader/lib/index.js
    You may need an additional loader to handle the result of these loaders.
    |
    | div
    >   background-color green
    |
     @ ./popup/App.vue?vue&type=style&index=0&lang=stylus& 1:0-129 1:145-148 1:150-276 1:150-276
     @ ./popup/App.vue
     @ ./popup/index.js

I've taken a look at webpack.config.js but I'm not enough of an expert to fix it and do a pull request, sorry.

**Comment by mubaidr** [comment]
I thik I removed stylus support. Please use css/scss/sass.
