### ISSUE TITLE
PurgeCSS plugin breaks Vuetify CSS

### ISSUE THREAD

**Issue by andrewmackie** [mubaidr/vue-chrome-extension-boilerplate#454]
Thanks for creating and maintaining this repo.

FYI when using Vuetify with this repo, the PurgeCSS plugin removes Vuetify's CSS.

The discussion at https://github.com/FullHuman/purgecss/issues/67 suggests that a loader might fix this - I tried https://github.com/americanexpress/purgecss-loader with the standard settings but it also stripped Vuetify's CSS.  This loader may, of course, work with different settings.

I won't be pursuing it further at this stage (I'm happy to have my code working without CSS purging) but am passing this on in case it's useful.

**Comment by mubaidr** [comment]
Well, I also think removing the `purgecss` plugin is most suitable option. Since we are developing extension here (which is essentially a zip file) most css libraries will only add ~5KB of extra css. Unless I am missing something. 

Though in future is someone needs it, we can try again.

**Comment by andrewmackie** [comment]
Yes, it doesn't save much. It's not a bug, though, so it's entirely up to you! 👍

**Comment by mubaidr** [comment]
Done: https://github.com/mubaidr/vue-chrome-extension-boilerplate/commit/a05b7adc54fff81508d6b38b38db72df019a2337
